#!/bin/sh

gksu rm /etc/cinnamon-desktop/*.ini
sudo cp ../../panels/panel.simple /etc/cinnamon-desktop/panel.ini
sudo rm /etc/xdg/autostart/*plank*
nohup cinnamon-panel --replace --reset &
sleep 5
gsettings set com.solus-project.cinnamon-menu:/com/solus-project/cinnamon-menu/ menu-headers false
gsettings set com.solus-project.cinnamon-menu:/com/solus-project/cinnamon-menu/ menu-compact "true"
gsettings set com.solus-project.cinnamon-menu:/com/solus-project/cinnamon-menu/ enable-menu-label "true"
gsettings set com.solus-project.cinnamon-wm button-style 'traditional'
pkill plank &


