#!/bin/sh

gksu rm /etc/cinnamon-desktop/*.ini
sudo cp ../../panels/panel.ubuntu-cinnamon /etc/cinnamon-desktop/panel.ini
sudo cp ../../panels/cinnamon-plank.desktop /etc/xdg/autostart
gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/ position 'bottom'
gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/ theme 'Gtk+'
gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/ alignment 'center'
gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/ hide-mode 'none'
gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/ icon-size '40'
nohup cinnamon-panel --replace --reset &
nohup plank &


